### ISSUE TITLE
Início Rápido

### ISSUE THREAD

**Issue by overlineink** [AfonsoMatElias/easy#1]
Adicione instruções de **Início rápido** ao `README.md` de preferência um RWE c/ [StackBlitz ](https://stackblitz.com/)para facilitar o teste da **lib**. Em seguida add **Guia de Contribuição** para casos em que sua lib não cobre, a comunidade adiciona.

**Comment by AfonsoMatElias** [comment]
O que é RWE mano??

**Comment by overlineink** [comment]
App Hero (**Real World Example**) ou coisa do género pra testar a **lib** de forma completa. Diferentes formas de uso dessa lib. Deixa também uma def. do que ela faz mais simples sem complicar o usuário entende? RWE sem fazer fork ou clone c/ StackBlitz.

De uma olhada nisso [aqui](https://github.com/pedronauck/docz)

**Comment by AfonsoMatElias** [comment]
Ahmn entendo...
Na realidade, fiz isso mas estão nas pastas easy.testform...

Mas farei isso mano!!
